### ISSUE TITLE
Separação de Backend / Frontend vs Monolito

### ISSUE THREAD

**Issue by lbighetti** [training-center/plataforma#1]
Gostaria de propor que façamos a aplicação em duas partes, o Frontend em uma e o Backend em outra.

A alternativa seria Monolito.

Por favor votem com joínha nos comments abaixo na sua escolha preferida.

**Comment by lbighetti** [comment]
Backend + Frontend

**Comment by lbighetti** [comment]
Monolito

**Comment by fernandofleury** [comment]
Não vamos discutir prós e contras das abordagens?

**Comment by woliveiras** [comment]
Uma coisa importante a ser levada em consideração: vamos precisar de uma API para listar mentores(as) e mentorados(as) para expor nossos dados para outras pessoas.

**Comment by Diego-Brocanelli** [comment]
Acredito que seria mais viável separar back end do front end,  sendo dois sistemas independentes. Onde o back end seria apenas uma API, com isso o app front end irá consumir os dados. 

Com isso deixamos aberto também a possibilidade da criação de app mobile.

**Comment by luxu** [comment]
Num axo boa idéia separar back do front não e sim uní-los

**Comment by fernandofleury** [comment]
lembrando que o monolito não impede em nenhum momento o backend de ser só uma API. o que define o monolito vai ser mais próximo do que é o stack e como queremos consumi-lo, do que como vamos expor a API.

**Comment by Diego-Brocanelli** [comment]
@luxu poderia explanar um pouco mais sobre seu ponto de vista?

**Comment by Diego-Brocanelli** [comment]
@fernandofleury concordo, porém,  o @woliveiras mencionou da necessidade de termos uma API por isso julguei que a melhor opção já é criar uma API. Porém,  sim um app monolito é uma opção.

**Comment by luxu** [comment]
Olha eu axo q tipow ter os dois no msm projeto seria legal pois assim poderíamos dividir as tarefas e agilizar o processo do q fzr dois sistemas idênticos, num tenho um feedback pra ajudar nessa minha idéia, mas nos meus projetos faço assim, pq penso q para o CRUD e ter uma maior segurança o back cuidaria tranquilamente e o front para podermos usar o poder do JS

**Comment by luxu** [comment]
agr me digam: o q seria esse monolito?

**Comment by luxu** [comment]
e com ctz SPA tem q ser usado

**Comment by hdamaich** [comment]
Constumo achar que a abordagem Backend + Frontend separa melhor as responsabilidades e acho que isso num projeto aberto facilita um pouco mais a separação do projeto em varias desenvolvedores.

**Comment by Diego-Brocanelli** [comment]
@luxu Acredito que não me fiz entender, pois a ideia que propus é justamente seguindo os conceitos que você listou, organizar/separar melhor as atividades e aproveitar o melhor dos dois mundos (back e front end) e não ter dois sistemas idênticos, pois cada sistema ficará responsável por realizar aquilo que lhe compete. 

Monolito = Ter toda a sua estrutura (back end e Front end) no mesmo base code do seu APP, em outras palavras tudo junto.

No ponto que listei acima, foi com o intuito de separar/organizar as responsabilidades.

Qual o motivo de utilizar uma SPA?

Espero que compreenda que estou levantando esses questionamentos pois é o foco desta issue, discutirmos qual arquitetura/tecnologia/banco de dados etc utilizaremos no sistema. Com isso a necessidade de compreender todos os argumentos de todos os membros da comunidade.

**Comment by mayronceccon** [comment]
Separando em API e front, futuramente poderá ser  feito integrações com outros sistemas, alterar front sem a necessidade de alterar o back. Eu sugeriria esta abordagem API + front

**Comment by raymonsanches** [comment]
Sob a minha perspectiva, se quisermos atrair mais contribuidores para o projeto, separar em um SPA faria mais sentido.

Assim temos uma camada de frontend, independente que pode atrair muito dev que nunca contribuiu em open source antes. Passa a ser possível até a separação em squads e a autonomia de linguagem de cada um além de facilitar a exposição da nossa API pra quem quiser consumir os dados e criar alguma lib third-party.

Uma coisa a se pensar também é que a aplicação pode ser dividida em: a camada de interação com o usuário final na forma de SPA e um backoffice (admin da aplicação) onde esse sim pode integrar a aplicação monolítica e onde basicamente ficariam os CRUDS que o @luxu comentou.

**Comment by woliveiras** [comment]
Galera, estávamos discutindo pelo Slack e acho que essas issues que abrimos irão mais atrasar o desenvolvimento do que ajudar a agilizar algo (visto que temos urgência nessa plataforma).

Pensei em logo assumirmos de criar algo igual o freeCodeCamp: https://github.com/freeCodeCamp/freeCodeCamp

Vamos?

Nodejs, frontend em React e bora!

A discussão agora seria somente para definir hospedagem e bancos de dados na #4 

Posso fechar essa issue e partimos pro desenvolvimento?

Só precisaremos de designer pra ajudar a montar as telas.

**Comment by Diego-Brocanelli** [comment]
Vendo os pontos que vc listou @owliveira já foi decidido o que estávamos discutindo aqui, nesse caso acredito que pode ser encerrado.

**Comment by Diego-Brocanelli** [comment]
@raymonsanches gostei dos pontos que você listou, poderíamos continuar essa conversa em outra ferramenta, tipo Telegram ou slack?

**Comment by gustavogodoi** [comment]
Para o Frontend, ja que vamos utilizar React, sugestao para nossa stack:
- React 16 com ES6
- Redux
- Webpack
- Mocha + expect + Enzyme - (testes)

Alguns extras:
- [Babel](https://babeljs.io/docs/plugins/preset-react) - utilizar E6 e suportar navegadores antigos.
- [Prettier](https://github.com/prettier/prettier) - normalizar o estilo de codigo e evitar discussoes (ex: 2 ou 4 espacos? aspas simples ou duplas?, etc)

Sugestoes?

**Comment by luxu** [comment]
tô fora enton nunca mechi com nd disso!!

**Comment by anony000** [comment]
Eu ia ajudar, eu juro que ia, até falarem que ia ser feito em React :(

**Comment by alinebastos** [comment]
A decisão, seja ela qual for, nunca vai agradar a todos.

Bom, sou parceira pra qualquer que seja a tecnologia :)

**Comment by woliveiras** [comment]
Achei excelente, @gustavogodoi 

Bora começar a fazer? 

Já podemos dar o start, da uma olhada: https://github.com/training-center/plataforma/issues/6

**Comment by woliveiras** [comment]
Galera, vou fechar essa issue por conta da decisão anterior de seguirmos o fluxo parecido com o do freeCodeCamp.

Qualquer coisa, abram outras issues individuais, viu. Valeu!
