### ISSUE TITLE
[front] Criar header de navegação

### ISSUE THREAD

**Issue by fernandofleury** [training-center/plataforma#11]
O header pode ser algo super simples. Inicialmente seria legal ter um com:

- [x] Logo
- [x] Link para cadastro
- [x] Link para login

No mobile talvez possamos usar um estilo hamburgão no menu e já eras.

**Comment by alinebastos** [comment]
Já tem layout pra isso? Se eu fosse boa nos designs eu faria isso rapidinho :P

**Comment by fernandofleury** [comment]
Acho que não temos layout 😢  é no olhometro

**Comment by alinebastos** [comment]
Me coloquei pra fazer, se eu não fizer hoje eu "me tiro", hehe.

**Comment by alinebastos** [comment]
Foi \o/

**Comment by fernandofleury** [comment]
🚀
