### ISSUE TITLE
SPA ou não SPA?

### ISSUE THREAD

**Issue by woliveiras** [training-center/plataforma#3]
Como na discussão aberta na issue #1 devemos planejar se iremos desenvolver uma SPA ou não.

## Vantagens da abordagem de SPA's

* melhor experiência do usuário (não precisa recarregar a página)
* mais fácil manutenção de código (ponto questionável se não tiver boa arquitetura)
* mais fácil de planejar uma arquitetura para o frontend
* mais fácil de reutilizar código
* mais fácil de escalar se tivermos uma boa arquitetura
* gasta menos dados do usuário (por não precisar recarregar a página o tempo todo)
* não importa o backend

## Desvantagens da SPA

* maior dificuldade se precisarmos de SEO
* precisaremos de pessoas com mais conhecimento em desenvolvimento de software do que desenvolvimento de sites institucionais
* workflow deve ser bem planejado para não atrapalhar o desenvolvimento (build)

## Vantagens do não SPA

* SEO

## Desvantagens do não SPA

* muitos recarregamentos
* preso ao backend

OBS: *Eu não me recordo muito quais as vantagens de não SPA, por isso podemos ir acrescentando pontos se mais alguém souber algo.*

**Não devemos discutir nessa issue se vamos usar jQuery, Angular, React, VueJS, mas se criaremos uma SPA ou não. Definido isso partiremos para a discussão da escolha da tecnologia**

**Comment by woliveiras** [comment]
## Sobre SEO

Não vejo necessidade de se pensar em SEO em nossa plataforma, pois não precisamos ranquear ela, nosso site deve fazer o papel de trazer o usuário até ela.

## O que eu acho mais importante para nossa plataforma

* experiência do usuário
* acessibilidade
* performance

**Comment by woliveiras** [comment]
Decidimos partir para o React: https://github.com/training-center/plataforma/issues/1#issuecomment-334153642

**Comment by danilosilvadev** [comment]
Eu acho que deveria ser react e ainda que quem fosse programar deveria fazer umas livestream durante o processo. Nem precisava explicar nada, só queria fuçar o processo dos outros rsrs.
