### ISSUE TITLE
Tecnologias de backend

### ISSUE THREAD

**Issue by woliveiras** [training-center/plataforma#4]
Assim que for definido a maneira como criaremos o backend (#1) podemos vir para essa issue discutir quais tecnologias serão utilizadas para isso.

## Pontos que precisaremos resolver

* hospedagem
* banco de dados
* plataforma de backend (Ruby, Node, Python, Elixir, etc)

## O que já dá para discutir

* hospedagem
* banco de dados

**Comment by luxu** [comment]
axo q Python e MongoDB seria uma boa

**Comment by hdamaich** [comment]
Acho que a hospedagem depende um pouco da Stack que vamos seguir, pois em alguns caso talvez o Heroku seja uma opção viável.
Também podemos usar a AWS (com RDS e Container Services).

**Comment by luxu** [comment]
essa da hospedagem realmente me pegou, pois axava q já estivesse uma hospedagem já contratada

**Comment by adeonir** [comment]
O site está hospedado direto aqui no github, o que está contratado é o domínio e o serviço da cloudflare.

**Comment by raymonsanches** [comment]
Olá, vocês já ouviram a palavra do PHP hoje? hahaha... Brinks...

Mas eu votaria em PHP, Rails ou NodeJS. Mais pela facilidade de botar um MVP já rodando o mais rápido possível.

**Comment by mayronceccon** [comment]
Um ponto que se deve pensar é em relação ao custo disso, não sei se o CT tem muitos patrocinadores, mas você desenvolver em Java e SqlServer é muito mais caro do que PHP e MariaDB.

**Comment by luxu** [comment]
axo q esse é o pto negativo...pelo q vejo num tem nd de patrocinador e as despesas devem sair dos nossos bolsos...

**Comment by adeonir** [comment]
@luxu para isso temos o [apoia.se](https://apoia.se/training-center)

**Comment by cenoura** [comment]
Vou deixar meus dois cents aqui:
Sobre servidor, utilizo os serviços de VPS da Vultr (https://www.vultr.com/), que começam com US$ 2.50/mês (512MB de RAM e 20GB de SSD). Rodo, tranquilamente, PHP, nginx, mysql, etc. Nada impede de rodarmos outra stack também.
Sobre tecnologias, como desenvolvo em PHP e JavaScript, iria de PHP ou NodeJS 😛

**Comment by woliveiras** [comment]
Galera, discutimos por slack e decidimos partir logo para o desenvolvimento.

Olhem esse comentário: 

https://github.com/training-center/plataforma/issues/1#issuecomment-334153642

Aqui só precisamos definir banco de dados e hospedagem com base nos requisitos.

**Comment by lbighetti** [comment]
Eu uso bastante Heroku.
boas experiencias com Digital Ocean e Linode também.

Banco de dados eu iria de Postgres, mas pouco importa eu acho, qualquer um dos principais vai dar conta.

**Comment by hdamaich** [comment]
Heroku parece ser uma ótima opção para nossa Stack

**Comment by khaosdoctor** [comment]
- Heroku é excelente para NodeJs
- Entre AWS, Azure e Google Cloud, prefiram GCloud porque ele é cobrado em reais e não em dólares, o que torna um pouco mais barato, mas não acho que haja a necessidade disso, seria um canhão
- O front pode estar hospedado em storages estáticos (como o S3 ou o GStorage) que são muito baratos e fáceis de usar
- Se formos utilizar outras tecnologias, já não aconselho tanto o heroku, podemos ficar com a Umbler também (que é excelente, uso em todos os projetos) ou a Digital Ocean

**Comment by khaosdoctor** [comment]
No quesito de banco de dados, ao meu ver, acho que o Mongo suporta, porém o suporte deverá ser mais complicado, porque não vamos ter nenhum tipo de regra de negócio no banco (como temos as relações entre tabelas em bancos relacionais), vamos ter que manter essas regras muito bem documentadas para evitar o problema que passo todos os dias no meu trabalho: dados duplicados em mais de uma collection

**Comment by khaosdoctor** [comment]
Como não tiveram muitas respostas aqui, vou montar mais ou menos uma base e podemos ver se fica legal pra todo mundo:

# Hospedagem

- [Umbler](umbler.com.br): Hospedagem simples de sites conectada com o github e etc
  - __Por que?:__ Cobrado em R$ e tambẽm é no modelo de crédito, ou seja, é pago por uso a partir de créditos pré carregados.
  - __Prós:__ Brasileiro, mais barato, contém muita coisa que a gente precisa
  - __Contras:__ Pode ser um pouco complicado de usar porque é um armazenamento de hospedagem para sites, não para API's
- [Heroku](heroku.com): Modelo de serviços focado em API's e microserviços
  - __Por que?:__ Excelente para API's e para Node ou qualquer outro tipo de linguagem disponível com um CLI simples e rápido.
  - __Prós:__ Simples de usar, não precisa de muitas configurações, robusto e escalável
  - __Contras:__ Cobrado em US$, pode ficar caro.

# Banco de dados

Nesse quesito acho que o Mongo resolve rápido e fácil, __mas__ não acho que é uma boa opção... Porque estamos trabalhando com um modelo estritamente e obviamente relacional... Eu acho melhor utilizarmos um banco de dados relacional (como o MySQL ou o Postgres) para podermos ter um controle maior sobre o que vamos fazer. Até porque isso não vai ser um sistema multinacional global que vai ter bilhões de pessoas tão rápido, por isso acho que NoSQL para esse caso não vale tanto a pena.

> Heroku e a Umbler já possuem integrações com esses bancos

# Linguagem

Pelo que queremos fazer, o Node seria mais interessante porque ele é justamente feito e modelado para construir API's... É ridiculamente simples criar uma API em node e temos 2^64 frameworks javascript por ai... __Plus__ a maioria das hospedagens como heroku tem o Node como ambiente nativo (no caso da Umbler, as plataformas PHP são mais legais).

**Comment by woliveiras** [comment]
Galera, acham interessante iniciar com um Heroku por conseguirmos algo free? 

Eu estou atrás de patrocínio para a hospedagem. :)

**Comment by fernandofleury** [comment]
soca tudo no heroku e vamo bora

**Comment by fernandofleury** [comment]
@woliveiras pior caso eu pago um .com.br pra gente e cabou

**Comment by luxu** [comment]
Axo q dá pra usar a minha hospedagem por hr tb...só uso ela para projetos pessoais no momento e num vejo uma luz q isso vá mudar a curto prazo

**Comment by adeonir** [comment]
Eu tenho uma revenda de hospedagem... tem node, mas acho que o acesso é meio restrito.
Digo 'acho' porque ainda não usei node lá

**Comment by woliveiras** [comment]
Galera, eu criei a conta no Heroku e vou adicionar no time (dar acesso ao Heroku) pelo Slack.

Podemos fechar essa issue, né?

**Comment by luxu** [comment]
se estiver td definido axo q sem problemas

**Comment by hdamaich** [comment]
@woliveiras @khaosdoctor O Banco vai ser MySQL mesmo ne?

**Comment by annacruz** [comment]
Pq o banco vai ser mysql? seria melhor optar pelo postgres não?

**Comment by woliveiras** [comment]
Concordo com o Postgre. O MySQL não é free. :cry:

**Comment by luxu** [comment]
Como num é free william? Uso ele há anos e pelo menos o básico nunca paguei 1 centavo

**Comment by woliveiras** [comment]
Versão community é free e tem suas "limitações": https://www.mysql.com/products/

* https://www.quora.com/Is-MySQL-free
* https://en.wikipedia.org/wiki/MySQL

PostgreSQL é free de verdade, @luxu: https://www.postgresql.org/

* https://www.quora.com/Is-PostgreSQL-free
* https://en.wikipedia.org/wiki/PostgreSQL

* https://www.digitalocean.com/community/tutorials/sqlite-vs-mysql-vs-postgresql-a-comparison-of-relational-database-management-systems

**Comment by luxu** [comment]
num sabia vlw

**Comment by lbighetti** [comment]
+1 Heroku & Postgres
Bora fechar @woliveiras

**Comment by woliveiras** [comment]
Sucesso!
