### ISSUE TITLE
Incrementar os requisitos com informações da plataforma atual

### ISSUE THREAD

**Issue by moraleida** [training-center/plataforma#5]
No [texto atual de requisitos](https://github.com/training-center/plataforma/blob/master/requisitos_plataforma.md) a explicação de quais problemas estamos querendo resolver com a nova plataforma parece meio misturada com o restante do texto. Existe uma menção às dificuldades no primeiro parágrafo e depois uma lista de requisitos sem uma definição clara do que já existe hoje e o que é novidade, ou de quais problemas são mais importantes pra se resolver.

Seria interessante fazer uma seção compilando os prós e contras existentes no gerenciamento atual via Github, ou seja, acrescentar todos os pontos positivos do Github como requisitos da nova plataforma, além de individualizar os problemas que a nova plataforma quer resolver. Isso pode ser só uma tabela tipo:

Pontos Positivos| Problemas a resolver
------------ | -------------
Facilidade de enviar PRs | Nem todo mundo sabe enviar PRs

Essa tabela então serviria como o primeiro checklist de qualidade, pra garantir que os pontos positivos continuam presentes na nova plataforma e os negativos foram resolvidos. (ou que se decidirmos por abandonar um pró o ou relevar um contra, que isso seja documentado no novo projeto)

**Comment by moraleida** [comment]
cc @woliveiras

**Comment by khaosdoctor** [comment]
Eu acho que a gente teria que fazer, na verdade, um catado geral de coisas que decidimos e colocarmos tudo em um README pra não ter que caçar issues kkk

**Comment by woliveiras** [comment]
Galera, o trampo na plataforma já está caminhando, acho que não compensa gastar tempo executando essa melhoria visto que o pessoal já está conseguindo se entender via slack e tudo mais.

Podemos fechar essa issue?

**Comment by khaosdoctor** [comment]
Acho que pelo slack dá pra pegar mais fácil e depois podemos usar o projects como disseram na #2
